### ISSUE TITLE
Performance optimizations

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/a-painter#222]
I'll collect here the list of issues related to performance improvement to have an overview vision of what we try to achieve and the status of each task:
- [ ] Fix bounding box issue having a point always on 0,0,0 when using drawRange with on buffer geometries (https://github.com/aframevr/a-painter/issues/217)
- [ ] Use a texture atlas to pack all the textures from the lines and stamps materials so we don't need to load more than one texture (https://github.com/aframevr/a-painter/issues/218).
- [ ] Use instances for brushes like spheres or cubes instead of creating a new mesh for each object. (https://github.com/aframevr/a-painter/issues/219)
- [ ] Use vertex colors instead of setting the `material.color` so strokes using the same brush but with different colors could be stored on a common buffergeometry. (https://github.com/aframevr/a-painter/issues/220)
- [ ]  Use big buffers and store there the vertices instead of one buffergeometry for each stroke. (https://github.com/aframevr/a-painter/issues/221)
